### ISSUE TITLE
lodash.memoize

### ISSUE THREAD

**Issue by GuskiS** [mgechev/memo-decorator#2]
Hello. Just watched your talk on ngconf and I wanted to see what is happening behind the scenes in this package.

I noticed that you are using `lodash.memoize` and immediately remembered this tweet:
https://twitter.com/dtinth/status/987533473064742912

Maybe it would be better to switch to other memozing library. First one that comes in mind is https://github.com/planttheidea/moize

**Comment by mboughaba** [comment]
It seems this was taken care of in `loadash v4.16.0` however the npm package `loadash.memoize` is not released yet. https://github.com/lodash/lodash/issues/4030

**Comment by mgechev** [comment]
In version 2 of the library you can specify a custom caching object.
